version: 2

updates:
  # Frontend Dependencies (Angular App)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      angular:
        patterns:
          - "@angular*"
      other-packages:
        patterns:
          - "*"
        exclude-patterns:
          - "@angular*"

  # Backend Dependencies (Node.js API)
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      angular:
        patterns:
          - "@angular*"
      other-packages:
        patterns:
          - "*"
        exclude-patterns:
          - "@angular*"
